# Generated by Django 5.0.1 on 2024-01-02 21:06

import django.db.models.deletion
import django_resized.forms
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAppPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('gerenciar_usuarios', 'Gerenciar Usuários')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('job_function', models.CharField(max_length=255, null=True, verbose_name='Cargo ou Função')),
                ('cpf', models.CharField(max_length=255, null=True, verbose_name='CPF')),
                ('bio', models.TextField(default=None, null=True, verbose_name='Biografia')),
                ('birthday', models.DateField(null=True, verbose_name='Data Nascimento')),
                ('avatar', django_resized.forms.ResizedImageField(crop=None, default='avatars/users/default-avatar.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[128, 128], upload_to='avatars/users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profile',
            },
        ),
    ]
