# Generated by Django 5.0.1 on 2024-03-26 11:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cc6ebb2c-3f5b-4c2b-a96c-48087bdebf02'), editable=False, unique=True),
        ),
    ]
