# Generated by Django 5.0.1 on 2024-02-28 09:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9bd1b897-2e25-4968-8ef6-848a9e2fc95e'), editable=False, unique=True),
        ),
    ]
