# Generated by Django 5.0.1 on 2024-02-28 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a481f191-98cc-4186-9443-c6911a5dfe90'), editable=False, unique=True),
        ),
    ]
