# Generated by Django 5.0.1 on 2024-01-03 14:27

import django.db.models.deletion
import django_resized.forms
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Municipios',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Código Município')),
                ('cod_uf', models.IntegerField(verbose_name='Código UF')),
                ('sigla_uf', models.CharField(max_length=2, null=True, verbose_name='Sigla UF')),
                ('nome_uf', models.CharField(max_length=255, null=True, verbose_name='Nome UF')),
                ('nome_municipio', models.CharField(max_length=255, null=True, verbose_name='Nome Município')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cadastro Municípios',
            },
        ),
        migrations.CreateModel(
            name='Categoria_Cadastro_Pessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Descrição Categoria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categoria Cadastro Pessoal',
            },
        ),
        migrations.CreateModel(
            name='Cadastro_Pessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('razao_social', models.CharField(max_length=255, null=True, verbose_name='Nome ou Razão Social')),
                ('natureza_juridica', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, null=True, verbose_name='Natureza Jurídica')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('cpf_cnpj', models.CharField(error_messages={'unique': 'CPF ou CNPJ já cadastrado!'}, max_length=40, null=True, unique=True, verbose_name='CPF/CNPJ')),
                ('numero_rg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('cep_endereco', models.CharField(blank=True, max_length=50, null=True, verbose_name='CEP')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data Nascimento')),
                ('contato_01', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato 01')),
                ('contato_02', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato 02')),
                ('email_01', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email 01')),
                ('email_02', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email 02')),
                ('profissao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('avatar', django_resized.forms.ResizedImageField(crop=None, default='avatars/clients/default-avatar.jpeg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[128, 128], upload_to='avatars/clients')),
                ('is_active', models.BooleanField(default=1, null=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.cadastro_municipios', verbose_name='Município')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.categoria_cadastro_pessoal', verbose_name='Categoria Cadastro')),
            ],
            options={
                'verbose_name_plural': 'Cadastro Pessoal',
            },
        ),
    ]
